- group: 1. Basic Model in Scene
  manifests:
    - name: Single Model
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/1_basic_model_in_scene/model_origin.json
    - name: Single Model with background color
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/1_basic_model_in_scene/model_origin_bgcolor.json
- group: 2. Cameras
  manifests: 
    - name: Model with Explicit Perspective Camera
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/2_cameras/perspective_camera.json
    - name: Model with Explicit Perspective Camera Looking at an Annotation
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/2_cameras/positioned_camera_lookat_anno.json
    - name: Model with Explicit Perspective Camera Looking at a Point
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/2_cameras/positioned_camera_lookat_point.json
    - name: Choice of cameras WARNING use of Choice
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/2_cameras/zz_choice_of_cameras.json
    - name: Orthographic Camera
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/2_cameras/zz_orthographic_camera.json
- group: 3. Lights
  manifests:
    - name: Model with Green AmbientLight
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/3_lights/ambient_green_light.json
    - name: Model with DirectionalLight
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/3_lights/direction_light_lookat_positioned.json
    - name: Model with Rotated DirectionalLight
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/3_lights/direction_light_transform_rotate.json
- group: 4. Transform and Position
  manifests:
    - name: Single Positioned Model
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/4_transform_and_position/model_position.json
    - name: Model shown normally and mirrored
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/4_transform_and_position/model_transform_negative_scale_position.json
    - name: Rotated Model
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/4_transform_and_position/model_transform_rotate_position.json
    - name: Rotated Translated Model
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/4_transform_and_position/model_transform_rotate_translate_position.json
    - name: Translated, Scaled Model with original for comparison
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/4_transform_and_position/model_transform_scale_position.json
    - name: Scaled, Translated Model with original for comparison
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/4_transform_and_position/model_transform_scale_translate_position.json
    - name: Translated Rotated Model
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/4_transform_and_position/model_transform_translate_rotate_position.json
    - name: Scaled Model with original for comparison
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/4_transform_and_position/model_transform_translate_scale_position.json
    - name: Whale Cranium and Mandible Positioned
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/4_transform_and_position/whale_cranium_and_mandible_position.json
- group: 5. Nesting
  manifests: []
- group: 6. 2D Canvases in Scene
  manifests:
    - name: Scene with a Canvas
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/6_2d_canvases_in_scene/iiif_canvas_with_bgcolor_backward.json
    - name: Scene with a Canvas (2)
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/6_2d_canvases_in_scene/iiif_canvas_with_bgcolor_forward.json
- group: 7. Excluding Model Features
  manifests: []
- group: 8. Scenes with Duration
  manifests: []
- group: 9. Commenting Annotations
  manifests:
    - name: Single Model with Comment Annotations
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/9_commenting_annotations/astronaut_comment.json
    - name: Whale Cranium and Mandible with Point Comment Annotation
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/9_commenting_annotations/whale_comment.json
    - name: Whale Cranium and Mandible with Point Comment Annotation and Camera
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/9_commenting_annotations/whale_comment_camera.json
    - name: Whale Cranium and Mandible with Point Comment Annotation Oriented Toward Camera
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/9_commenting_annotations/whale_comment_label_body_position.json
    - name: Whale Cranium and Mandible with Point Comment Annotation Oriented Toward Camera (2)
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/9_commenting_annotations/whale_comment_label_body_position_rotate.json
    - name: Whale Cranium and Mandible with Point and 2D Shape Comment Annotations
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/9_commenting_annotations/whale_comment_point_polygon.json
- group: 10. Content State
  manifests:
    - name: Single Model with Comment Annotations and Custom Views Per Annotation
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/10_content_state/astronaut_comment_scope.json
    - name: Whale Cranium and Mandible with Dynamic Commenting Annotations and Custom Per-Anno Views
      url: https://raw.githubusercontent.com/IIIF/3d/main/manifests/10_content_state/whale_comment_scope_content_state.json





    - name:
      url: 