- name: Aleph + UV (MorphoSource)
  url: https://morphosource.github.io/universalviewer/uv.html#?manifest=
- name: Kompakkt
  url: https://kompakkt.github.io/Viewer/?locale=en&standalone=true&manifest=
- name: Voyager (Smithsonian)
  url: https://smithsonian.github.io/voyager-dev/iiif/iiif_demo.html?document=
- name: X_ITE Viewer
  url: https://www.kshell.com/pages/iiif3d/x_ite/view/index.html?manifest=
